main: net.craftcitizen.imagemaps.ImageMaps
author: SydMontague
version: ${project.version}
api-version: 1.13
name: ImageMaps
commands:
    nfts:
        description: ImageMaps plugin commands, place images on walls
        permission-message: You do not have permission to use this command.
        usage: |
          /nfts place <nftName> [size] - starts nft placement
          /nfts delete <nftName> - deletes an image
          /nfts info <nftName> - displays image info
          /nfts reload <nftName> - reloads an image from disk
          /nfts list [page] - lists all files in the images folder
          /nfts help [command] - shows help